packages:
  - apps/*
  - packages/*
ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - bcrypt
  - core-js
  - prisma
  - sharp
  - unrs-resolver
