// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
    "login":{
        "heading": "login",
        "form":{
            "email":"Email",
            "password":"Password",
            "submit":"Submit",
            "submiting":"Submiting..."
        },
        "newHere":"New Here?",
        "createAnAccount":"Create an Account!"
    }
};
export default messages;